### ISSUE TITLE
url-shortener: final touches

### ISSUE THREAD

**Issue by giolekva** [giolekva/pcloud#68]
- [x] Make listen port configurable instead of hardcoding `8080` https://github.com/giolekva/pcloud/blob/71353b5b7b2516a5dbb2005de5623c2bf89493f6/apps/rpuppy/main.go#L13
- [x] Use light theme: https://picocss.com/docs/themes.html
- [x] Use container to center the contents: https://picocss.com/docs/containers.html
- [x] Move `toggle` javascript function into a separate file: `/static/main.js` and include it in the html using `<script src="/static/main.js" ...`
- [x] Download `pico.min.css` from https://github.com/picocss/pico/archive/refs/tags/v1.5.11.zip and handle it from `/static` folder

Static file handler example: https://gist.github.com/giolekva/be8d4ee46d65f17d3a61a39ba80cb5af

**Comment by DTabidze** [comment]
All Done
